
let os = substitute(system('uname'), "\n", "", "")
let hostname = substitute(system('hostname'), "\n", "", "")
if os == "Darwin"
    set guifont=Menlo\ Regular:h12
else
    if hostname == "irukandji"
        set guifont=DejaVu\ Sans\ Mono\ 8
    elseif hostname == "pearlscale"
        set guifont=DejaVu\ Sans\ Mono\ 20
    else
        set guifont=DejaVu\ Sans\ Mono\ 10
    endif
endif

set columns=175
set lines=60
colorscheme rndstr

function! GuiTabLabel()
    " add the tab number
    let label = '['.tabpagenr()
 
    " modified since the last save?
    let buflist = tabpagebuflist(v:lnum)
    for bufnr in buflist
        if getbufvar(bufnr, '&modified')
            let label .= '*'
            break
        endif
    endfor
 
    " count number of open windows in the tab
    let wincount = tabpagewinnr(v:lnum, '$')
    if wincount > 1
        let label .= ', '.wincount
    endif
    let label .= '] '
 
    " add the file name without path information
    let n = bufname(buflist[tabpagewinnr(v:lnum) - 1])
    let label .= fnamemodify(n, ':t')
 
    return label
endfunction
 
set guitablabel=%{GuiTabLabel()}
set guioptions-=m "menubar
set guioptions-=T "toolbar
set guioptions-=r "scrollbar
"
