autoload -Uz compinit
compinit
HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000
setopt extended_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt INC_APPEND_HISTORY

autoload -U colors
colors

# allow functions in prompt
setopt PROMPT_SUBST

# no beep
command -v xset >/dev/null 2>&1 && {
    xset -b 2>/dev/null #turn off beep
    xset r rate 250 50 2>/dev/null #faster kbd
}

# load functions
for i in ~/.dotfiles/zsh/functions/*; do 
    source $i
done

[ -f ~/.zshrc.local ] && source ~/.zshrc.local

export EDITOR="vim"
export BROWSER="chromium"

export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
#export LESS=-r

export PATH="/usr/share/perl5/vendor_perl/auto/share/dist/Cope:$PATH"
export PATH="$PATH:/usr/local/bin:${HOME}/.dotfiles/bin:${HOME}/bin"

export NVM_DIR="/home/rndstr/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

bindkey -v
bindkey "^R" history-incremental-search-backward
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/rndstr/.zshrc'

# End of lines added by compinstall

