autoload -U colors
colors

# allow functions in prompt
setopt PROMPT_SUBST

# load functions
for i in ~/.dotfiles/zsh/functions/*; do 
    source $i
done

export EDITOR="vim"

export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
#export LESS=-r

export PATH="/usr/share/perl5/vendor_perl/auto/share/dist/Cope:$PATH"
export PATH="$PATH:/usr/local/bin:${HOME}/.dotfiles/bin:${HOME}/bin"


# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=100000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/rndstr/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
